const API_TIMEOUT = 15000;
const QUERY_RETRY_COUNT = 1;
const QUERY_STALE_TIME = 1000 * 30; // 30 seconds
const QUERY_GC_TIME = 1000 * 60 * 5; // 5 minutes
const QUERY_REFETCH_ON_WINDOW_FOCUS = false;
const QUERY_MUTATION_RETRY_COUNT = 0;

export {
  API_TIMEOUT,
  QUERY_RETRY_COUNT,
  QUERY_STALE_TIME,
  QUERY_GC_TIME,
  QUERY_REFETCH_ON_WINDOW_FOCUS,
  QUERY_MUTATION_RETRY_COUNT,
};
